apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdply
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nnginxbox
          image: ravi955/nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "120m"
              memory: "215Mi"
            limits:
              cpu: "500m"
              memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: NodePort

