apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: dev
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: ravi955/tomcat:latest
    ports:
    - containerPort: 8080
